module.exports = {
  API_VALIDATION_ERROR: "API_VALIDATION_ERROR",
  DB_VALIDATION_ERROR: "DB_VALIDATION_ERROR",
  DB_ERROR: "DB_ERROR",
  EXT_API_ERROR: "EXT_API_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
};
